### ISSUE TITLE
need garak

### ISSUE THREAD

**Issue by wearetyomsmnv** [RiccardoBiosas/awesome-MLSecOps#1]
hi. add this tool in your list https://github.com/leondz/garak

**Comment by RiccardoBiosas** [comment]
@wearetyomsmnv thanks for the tip!

**Comment by anmorgan24** [comment]
Hi there! Lakera AI has some really cool products (they're the ones behind the Gandalf prompt injection game)

**Comment by RiccardoBiosas** [comment]
@anmorgan24 Gandalf is very neat, i've just added it to the resources. appreciate the suggestion!
